CA:
  - '93637'
  - 500
  - [CA, NV]
AZ:
  - '85547'
  - 250
  - [AZ]
OR:
  - '97756'
  - 250
  - [OR]
WA:
  - '98801'
  - 250
  - [WA]
UT:
  - '84627'
  - 250
  - [UT]
CO:
  - '80829'
  - 250
  - [CO]
MT:
  - '59014'
  - 500
  - [MT, ID, WY]
NM:
  - '87101'
  - 250
  - [NM]
TX:
  - '76884'
  - 500
  - [TX, OK]
ND:
  - '57029'
  - 500
  - [ND, SD, NE, IA, MN, KS]
TN:
  - '38069'
  - 500
  - [TN, MO, AR, IL, IN, MS, KY, AL, LA]
GA:
  - '31419'
  - 500
  - [GA, FL, NC, SC]
NY:
  - '14867'
  - 500
  - [VA, WV, OH, PA, NY, NJ, DE, CT, RI, MA, NH, VT, ME]
